// Code generated for service

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	auth_v1 "github.com/max-kriv0s/go-microservices-edu/shared/pkg/proto/auth/v1"

	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// IamServiceClient is an autogenerated mock type for the IamServiceClient type
type IamServiceClient struct {
	mock.Mock
}

type IamServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *IamServiceClient) EXPECT() *IamServiceClient_Expecter {
	return &IamServiceClient_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with given fields: ctx, req, opts
func (_m *IamServiceClient) Login(ctx context.Context, req *auth_v1.LoginRequest, opts ...grpc.CallOption) (*auth_v1.LoginResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, req)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *auth_v1.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *auth_v1.LoginRequest, ...grpc.CallOption) (*auth_v1.LoginResponse, error)); ok {
		return rf(ctx, req, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *auth_v1.LoginRequest, ...grpc.CallOption) *auth_v1.LoginResponse); ok {
		r0 = rf(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth_v1.LoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *auth_v1.LoginRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IamServiceClient_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type IamServiceClient_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - req *auth_v1.LoginRequest
//   - opts ...grpc.CallOption
func (_e *IamServiceClient_Expecter) Login(ctx interface{}, req interface{}, opts ...interface{}) *IamServiceClient_Login_Call {
	return &IamServiceClient_Login_Call{Call: _e.mock.On("Login",
		append([]interface{}{ctx, req}, opts...)...)}
}

func (_c *IamServiceClient_Login_Call) Run(run func(ctx context.Context, req *auth_v1.LoginRequest, opts ...grpc.CallOption)) *IamServiceClient_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*auth_v1.LoginRequest), variadicArgs...)
	})
	return _c
}

func (_c *IamServiceClient_Login_Call) Return(_a0 *auth_v1.LoginResponse, _a1 error) *IamServiceClient_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IamServiceClient_Login_Call) RunAndReturn(run func(context.Context, *auth_v1.LoginRequest, ...grpc.CallOption) (*auth_v1.LoginResponse, error)) *IamServiceClient_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Whoami provides a mock function with given fields: ctx, req, opts
func (_m *IamServiceClient) Whoami(ctx context.Context, req *auth_v1.WhoamiRequest, opts ...grpc.CallOption) (*auth_v1.WhoamiResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, req)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Whoami")
	}

	var r0 *auth_v1.WhoamiResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *auth_v1.WhoamiRequest, ...grpc.CallOption) (*auth_v1.WhoamiResponse, error)); ok {
		return rf(ctx, req, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *auth_v1.WhoamiRequest, ...grpc.CallOption) *auth_v1.WhoamiResponse); ok {
		r0 = rf(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth_v1.WhoamiResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *auth_v1.WhoamiRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IamServiceClient_Whoami_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Whoami'
type IamServiceClient_Whoami_Call struct {
	*mock.Call
}

// Whoami is a helper method to define mock.On call
//   - ctx context.Context
//   - req *auth_v1.WhoamiRequest
//   - opts ...grpc.CallOption
func (_e *IamServiceClient_Expecter) Whoami(ctx interface{}, req interface{}, opts ...interface{}) *IamServiceClient_Whoami_Call {
	return &IamServiceClient_Whoami_Call{Call: _e.mock.On("Whoami",
		append([]interface{}{ctx, req}, opts...)...)}
}

func (_c *IamServiceClient_Whoami_Call) Run(run func(ctx context.Context, req *auth_v1.WhoamiRequest, opts ...grpc.CallOption)) *IamServiceClient_Whoami_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*auth_v1.WhoamiRequest), variadicArgs...)
	})
	return _c
}

func (_c *IamServiceClient_Whoami_Call) Return(_a0 *auth_v1.WhoamiResponse, _a1 error) *IamServiceClient_Whoami_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IamServiceClient_Whoami_Call) RunAndReturn(run func(context.Context, *auth_v1.WhoamiRequest, ...grpc.CallOption) (*auth_v1.WhoamiResponse, error)) *IamServiceClient_Whoami_Call {
	_c.Call.Return(run)
	return _c
}

// NewIamServiceClient creates a new instance of IamServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIamServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *IamServiceClient {
	mock := &IamServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
