// Code generated for service

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/max-kriv0s/go-microservices-edu/order/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// PaymentServiceClient is an autogenerated mock type for the PaymentServiceClient type
type PaymentServiceClient struct {
	mock.Mock
}

type PaymentServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *PaymentServiceClient) EXPECT() *PaymentServiceClient_Expecter {
	return &PaymentServiceClient_Expecter{mock: &_m.Mock}
}

// PayOrder provides a mock function with given fields: ctx, order, paymentMethod
func (_m *PaymentServiceClient) PayOrder(ctx context.Context, order model.Order, paymentMethod model.PaymentMethod) (string, error) {
	ret := _m.Called(ctx, order, paymentMethod)

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Order, model.PaymentMethod) (string, error)); ok {
		return rf(ctx, order, paymentMethod)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Order, model.PaymentMethod) string); ok {
		r0 = rf(ctx, order, paymentMethod)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Order, model.PaymentMethod) error); ok {
		r1 = rf(ctx, order, paymentMethod)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PaymentServiceClient_PayOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayOrder'
type PaymentServiceClient_PayOrder_Call struct {
	*mock.Call
}

// PayOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order model.Order
//   - paymentMethod model.PaymentMethod
func (_e *PaymentServiceClient_Expecter) PayOrder(ctx interface{}, order interface{}, paymentMethod interface{}) *PaymentServiceClient_PayOrder_Call {
	return &PaymentServiceClient_PayOrder_Call{Call: _e.mock.On("PayOrder", ctx, order, paymentMethod)}
}

func (_c *PaymentServiceClient_PayOrder_Call) Run(run func(ctx context.Context, order model.Order, paymentMethod model.PaymentMethod)) *PaymentServiceClient_PayOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Order), args[2].(model.PaymentMethod))
	})
	return _c
}

func (_c *PaymentServiceClient_PayOrder_Call) Return(_a0 string, _a1 error) *PaymentServiceClient_PayOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PaymentServiceClient_PayOrder_Call) RunAndReturn(run func(context.Context, model.Order, model.PaymentMethod) (string, error)) *PaymentServiceClient_PayOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewPaymentServiceClient creates a new instance of PaymentServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentServiceClient {
	mock := &PaymentServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
