with-expecter: true
boilerplate-file: '.mockery_boilerplate_text.txt'
dir: '{{.InterfaceDir}}/mocks'
filename: 'mock_{{.InterfaceNameSnake}}.go'
outpkg: 'mocks'
mockname: '{{.InterfaceName}}'
resolve-type-alias: False
issue-845-fix: True

packages:
  github.com/max-kriv0s/go-microservices-edu/payment/internal/service:
    config:
      include-regex: '.*Service'

  github.com/max-kriv0s/go-microservices-edu/order/internal/service:
    config:
      include-regex: '.*Service'

  github.com/max-kriv0s/go-microservices-edu/order/internal/repository:
    config:
      include-regex: '.*Repository'

  github.com/max-kriv0s/go-microservices-edu/order/internal/client/grpc:
    config:
      include-regex: '.*Client'

  github.com/max-kriv0s/go-microservices-edu/inventory/internal/service:
    config:
      include-regex: '.*Service'

  github.com/max-kriv0s/go-microservices-edu/inventory/internal/repository:
    config:
      include-regex: '.*Repository'
