// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/google/uuid"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// APIV1OrdersOrderUUIDCancelPostParams is parameters of POST /api/v1/orders/{order_uuid}/cancel operation.
type APIV1OrdersOrderUUIDCancelPostParams struct {
	// Идентификатор заказа.
	OrderUUID uuid.UUID
	// UUID сессии пользователя для аутентификации.
	XSessionUUID uuid.UUID
}

func unpackAPIV1OrdersOrderUUIDCancelPostParams(packed middleware.Parameters) (params APIV1OrdersOrderUUIDCancelPostParams) {
	{
		key := middleware.ParameterKey{
			Name: "order_uuid",
			In:   "path",
		}
		params.OrderUUID = packed[key].(uuid.UUID)
	}
	{
		key := middleware.ParameterKey{
			Name: "X-Session-Uuid",
			In:   "header",
		}
		params.XSessionUUID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeAPIV1OrdersOrderUUIDCancelPostParams(args [1]string, argsEscaped bool, r *http.Request) (params APIV1OrdersOrderUUIDCancelPostParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode path: order_uuid.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "order_uuid",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.OrderUUID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "order_uuid",
			In:   "path",
			Err:  err,
		}
	}
	// Decode header: X-Session-Uuid.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "X-Session-Uuid",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.XSessionUUID = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "X-Session-Uuid",
			In:   "header",
			Err:  err,
		}
	}
	return params, nil
}

// APIV1OrdersOrderUUIDGetParams is parameters of GET /api/v1/orders/{order_uuid} operation.
type APIV1OrdersOrderUUIDGetParams struct {
	// Идентификатор заказа.
	OrderUUID uuid.UUID
	// UUID сессии пользователя для аутентификации.
	XSessionUUID uuid.UUID
}

func unpackAPIV1OrdersOrderUUIDGetParams(packed middleware.Parameters) (params APIV1OrdersOrderUUIDGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "order_uuid",
			In:   "path",
		}
		params.OrderUUID = packed[key].(uuid.UUID)
	}
	{
		key := middleware.ParameterKey{
			Name: "X-Session-Uuid",
			In:   "header",
		}
		params.XSessionUUID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeAPIV1OrdersOrderUUIDGetParams(args [1]string, argsEscaped bool, r *http.Request) (params APIV1OrdersOrderUUIDGetParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode path: order_uuid.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "order_uuid",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.OrderUUID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "order_uuid",
			In:   "path",
			Err:  err,
		}
	}
	// Decode header: X-Session-Uuid.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "X-Session-Uuid",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.XSessionUUID = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "X-Session-Uuid",
			In:   "header",
			Err:  err,
		}
	}
	return params, nil
}

// CreateOrderParams is parameters of CreateOrder operation.
type CreateOrderParams struct {
	// UUID сессии пользователя для аутентификации.
	XSessionUUID uuid.UUID
}

func unpackCreateOrderParams(packed middleware.Parameters) (params CreateOrderParams) {
	{
		key := middleware.ParameterKey{
			Name: "X-Session-Uuid",
			In:   "header",
		}
		params.XSessionUUID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeCreateOrderParams(args [0]string, argsEscaped bool, r *http.Request) (params CreateOrderParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: X-Session-Uuid.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "X-Session-Uuid",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.XSessionUUID = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "X-Session-Uuid",
			In:   "header",
			Err:  err,
		}
	}
	return params, nil
}

// PayOrderParams is parameters of PayOrder operation.
type PayOrderParams struct {
	// Идентификатор заказа.
	OrderUUID uuid.UUID
	// UUID сессии пользователя для аутентификации.
	XSessionUUID uuid.UUID
}

func unpackPayOrderParams(packed middleware.Parameters) (params PayOrderParams) {
	{
		key := middleware.ParameterKey{
			Name: "order_uuid",
			In:   "path",
		}
		params.OrderUUID = packed[key].(uuid.UUID)
	}
	{
		key := middleware.ParameterKey{
			Name: "X-Session-Uuid",
			In:   "header",
		}
		params.XSessionUUID = packed[key].(uuid.UUID)
	}
	return params
}

func decodePayOrderParams(args [1]string, argsEscaped bool, r *http.Request) (params PayOrderParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode path: order_uuid.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "order_uuid",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.OrderUUID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "order_uuid",
			In:   "path",
			Err:  err,
		}
	}
	// Decode header: X-Session-Uuid.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "X-Session-Uuid",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.XSessionUUID = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "X-Session-Uuid",
			In:   "header",
			Err:  err,
		}
	}
	return params, nil
}
