// Code generated by ogen, DO NOT EDIT.
package order_v1

type APIV1OrdersOrderUUIDCancelPostRes interface {
	aPIV1OrdersOrderUUIDCancelPostRes()
}

type APIV1OrdersOrderUUIDGetRes interface {
	aPIV1OrdersOrderUUIDGetRes()
}

type CreateOrderRes interface {
	createOrderRes()
}

type PayOrderRes interface {
	payOrderRes()
}
