// Code generated by ogen, DO NOT EDIT.

package order_v1

// OperationName is the ogen operation name
type OperationName = string

const (
	APIV1OrdersOrderUUIDCancelPostOperation OperationName = "APIV1OrdersOrderUUIDCancelPost"
	APIV1OrdersOrderUUIDGetOperation        OperationName = "APIV1OrdersOrderUUIDGet"
	CreateOrderOperation                    OperationName = "CreateOrder"
	PayOrderOperation                       OperationName = "PayOrder"
)
