// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// APIV1OrdersOrderUUIDCancelPost implements POST /api/v1/orders/{order_uuid}/cancel operation.
//
// CancelOrder.
//
// POST /api/v1/orders/{order_uuid}/cancel
func (UnimplementedHandler) APIV1OrdersOrderUUIDCancelPost(ctx context.Context, params APIV1OrdersOrderUUIDCancelPostParams) (r APIV1OrdersOrderUUIDCancelPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV1OrdersOrderUUIDGet implements GET /api/v1/orders/{order_uuid} operation.
//
// GetOrderById.
//
// GET /api/v1/orders/{order_uuid}
func (UnimplementedHandler) APIV1OrdersOrderUUIDGet(ctx context.Context, params APIV1OrdersOrderUUIDGetParams) (r APIV1OrdersOrderUUIDGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateOrder implements CreateOrder operation.
//
// Создаёт новый заказ на основе выбранных
// пользователем деталей.
//
// POST /api/v1/orders
func (UnimplementedHandler) CreateOrder(ctx context.Context, req *CreateOrderRequestDto) (r CreateOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PayOrder implements PayOrder operation.
//
// Оплата заказа.
//
// POST /api/v1/orders/{order_uuid}/pay
func (UnimplementedHandler) PayOrder(ctx context.Context, req *PayOrderRequestDto, params PayOrderParams) (r PayOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *GenericErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *GenericErrorStatusCode) {
	r = new(GenericErrorStatusCode)
	return r
}
